apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: ENV version 2
  labels:
    app: hello
  name: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
      env: dev
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello
        env: dev
    spec:
      initContainers:
        - name: status
          image: busybox:1.28
          volumeMounts:
            - name: status
              mountPath: /mnt
          command:
            - sh
            - -c
            - echo OK > /mnt/status
      containers:
      - image: bob2606/hello-http:0.8.34
        name: hello-http
        volumeMounts:
          - name: status
            mountPath: /var/lib/hello-http
        envFrom:
          - configMapRef:
              name: hello-env
        env:
          - name: ENV
            value: Micro-TP n°7 - Version 2
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        livenessProbe:
          httpGet:
            path: /livez
            port: 80
          periodSeconds: 5
          failureThreshold: 4
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 2
          failureThreshold: 3
        resources: {}

      volumes:
        - name: status
          emptyDir:
