apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello
  name: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
      env: dev
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello
        env: dev
    spec:
      containers:
      - image: bob2606/hello-http:0.8.34
        name: hello-http
        envFrom:
          - configMapRef:
              name: hello-env
        env:
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        livenessProbe:
          httpGet:
            path: /livez
            port: 80
          periodSeconds: 5
          failureThreshold: 4
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 2
          failureThreshold: 3
        resources: {}
status: {}
