apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: www
  name: www
spec:
  replicas: 3
  selector:
    matchLabels:
      app: www
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: www
    spec:
      containers:
        - image: nginx:1.28
          name: nginx
          env:
            - name: STAGE
              value: Kubernetes
            - name: IPADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: INTERVENTION
              valueFrom:
                configMapKeyRef:
                  name: www-env
                  key: FORMATION
          envFrom:
            - configMapRef:
                name: www-env
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            periodSeconds: 10
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            periodSeconds: 4
            failureThreshold: 2
          resources: {}
        - image: php:8.2-fpm
          name: php
          resources: {}
status: {}
